export const FACEBOOK_USER_DATA = 'FACEBOOK_USER_DATA';
export const INSTAGRAM_USER_DATA = 'INSTAGRAM_USER_DATA';
export const TWITTER_USER_DATA = 'TWITTER_USER_DATA';

export const OPEN_FACEBOOK_LOGIN = 'OPEN_FACEBOOK_LOGIN';
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';

export const OPEN_INSTAGRAM_LOGIN = 'OPEN_FACEBOOK_LOGIN';
export const INSTAGRAM_LOGIN = 'INSTAGRAM_LOGIN';
export const INSTAGRAM_LOGIN_FAIL = 'INSTAGRAM_LOGIN_FAIL';
export const INSTAGRAM_LOGIN_SUCCESS = 'INSTAGRAM_LOGIN_SUCCESS';

export const OPEN_TWITTER_LOGIN = 'OPEN_FACEBOOK_LOGIN';
export const TWITTER_LOGIN = 'TWITTER_LOGIN';
export const TWITTER_LOGIN_FAIL = 'TWITTER_LOGIN_FAIL';
export const TWITTER_LOGIN_SUCCESS = 'TWITTER_LOGIN_SUCCESS';

export const OPEN_DEFAULT_LOGIN = 'OPEN_DEFAULT_LOGIN';
